# -*- coding: utf-8 -*-
"""feature correlation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fHFnl9LD5DLP2JSEhdrF5_Pjf887GuG
"""

import pandas as pd

# Load dataset
df = pd.read_csv("EV_Charging_Load_Demand_Dataset.csv")

# Selected important features + target
features = [
    "station_vehicles_charging",
    "congestion_ratio",
    "load_per_vehicle_kW"
]
target = "station_power_demand_kW"

data = df[features + [target]]
data.head()

# Correlation matrix
corr_matrix = data.corr(method="pearson")
corr_matrix

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(7,5))
sns.heatmap(
    corr_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".3f",
    linewidths=0.5
)
plt.title("Feature Correlation Matrix")
plt.show()

target_corr = corr_matrix[target].sort_values(ascending=False)
target_corr

plt.figure(figsize=(6,4))
target_corr.drop(target).plot(kind="bar")
plt.ylabel("Correlation with station_power_demand_kW")
plt.title("Feature–Target Correlation")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

sns.pairplot(data, diag_kind="kde")
plt.show()

corr_table = target_corr.reset_index()
corr_table.columns = ["Feature", "Correlation_with_Power_Demand"]
corr_table